import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Jersey_10 } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { neobrutalism } from '@clerk/themes'
import { Toaster } from "@/components/ui/sonner"
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const gamefont = Jersey_10({
  variable: "--font-game",
  subsets: ["latin"],
  weight:'400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable}
            ${gamefont.variable} ${inter.variable} antialiased` }
          >
              <Provider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
            {children}
            <Toaster/>
            </Provider>
          </body>
        </html>
    </ClerkProvider>
  );
}
